name: build  image to DockerHub
on:
  workflow_dispatch:
  push:
    branches:
      - ecx-*
  pull_request:
    branches:
      - ecx-*
env:
  CONTAINER_RUN_OPTIONS: " "

jobs:
  publish-image-to-dockerhub:
    name: publish to DockerHub
    strategy:
      matrix:
        target:
          - cloudcore
    runs-on: ubuntu-18.04
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          # fetch-depth:
          # 0 indicates all history for all branches and tags.
          # for `git describe --tags` in Makefile.
          fetch-depth: 0
      - name: install QEMU
        uses: docker/setup-qemu-action@v1
      - name: install Buildx
        uses: docker/setup-buildx-action@v1
      - name: login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and publish images
        env:
          IMAGE_REPO_NAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: make crossbuildimage WHAT=${{ matrix.target }}
